export default {
  colors: {
    primary: '#1f1c2c',
    primaryLight: '',
    primaryLightest: '',
    primaryDark: '',
    primaryDarkest: '',
    secondary: '#928dab',
    secondaryLight: '',
    secondaryLightest: '',
    secondaryDark: '',
    secondaryDarkest: '',
    highlight: '#F45C43',
    highlightGradient: 'linear-gradient(to right, #eb3349, #f45c43)',
    black: '#333',
    white: '#fff',
    lightGray: '#444',
    gray: '#666',
    darkGray: '#888',
    gradient: 'linear-gradient(to right, #1f1c2c, #928dab)',
    error: '#f44343',
  },
};
